version: "3"
services:
  postgresdb:
    image: postgres:alpine
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=myDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Thisisngo1995!

  express-server:
    build: ./server
    container_name: express-server
    image: seismvpv1.azurecr.io/express-server
    environment:
      - CONNECTION_STRING=postgresdb://postgres:Thisisngo1995!@postgresdb:5432/myDB
      - DB_SERVER=postgresdb
      - DB_HOST=postgresdb
      - NODE_ENV=production
    links:
      - postgresdb
    depends_on:
      - postgresdb
    ports:
      - "3000:3000"

  react-app:
    build: ./client
    image: seismvpv1.azurecr.io/react-app
    container_name: reactApp
    ports:
      - "80:80"
    depends_on:
      - express-server
    environment:
      - REACT_APP_API_URL=http://localhost:4000
      - API_URL=http://localhost:4000
