version: "3.7"
services:
  postgresDB:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Thisisngo1995!
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  express-server:
    image: albertngo/express
    depends_on:
      - postgresDB
    ports:
      - "3000:3000"
